manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 9d714c0b69fee2098a010d29e534051aeca26386
      import: app/west.yml
  self:
    path: config
